import { BattleData } from "./types";

export const ankaraData: BattleData = {
  battleMetadata: {
    name: "Battle of Ankara",
    date: "20 July 1402",
    location: "Cubuk Plain, northeast of Ankara, Anatolia",
    belligerents: ["Ottoman Empire", "Timurid Empire"],
    commanders: [
      ["Bayezid I", "Suleyman Celebi", "Musa Celebi", "Stefan Lazarevic"],
      ["Timur", "Shah Rukh", "Miran Shah", "Khalil Sultan"],
    ],
    outcome: "Decisive Timurid victory; Bayezid captured",
    scale: "Approx. 80,000-90,000 Ottomans vs 120,000-140,000 Timurids",
  },

  context:
    "By 1402, Bayezid I had rapidly absorbed many Anatolian beyliks while pressuring Constantinople, and his rise put him on a collision course with Timur, whose empire stretched across Central Asia, Iran, and beyond. Dispossessed Anatolian rulers sought Timur's protection and urged intervention, turning a dynastic rivalry into a strategic confrontation over eastern Anatolia.\\n\\nTimur advanced into Anatolia with a larger and more operationally flexible army, then maneuvered around Bayezid, forcing the Ottomans into a punishing countermarch in summer heat. By the time the armies met near Ankara, Timur had already shaped the battlefield through logistics and water control, while Bayezid's forces were fatigued and partially brittle in loyalty.\\n\\nThe battle became a classic case where pre-battle preparation, political warfare, and cavalry maneuver decided the outcome as much as direct shock combat. Mid-battle defections from Bayezid's Anatolian elements, combined with Timurid encirclement pressure, shattered Ottoman cohesion and led to the capture of the sultan.",

  terrain: [
    {
      type: "river",
      label: "Cubuk Stream",
      points: [
        { x: 73, y: 0 },
        { x: 71, y: 14 },
        { x: 74, y: 27 },
        { x: 76, y: 40 },
        { x: 74, y: 54 },
        { x: 72, y: 69 },
        { x: 74, y: 86 },
        { x: 73, y: 100 },
      ],
      width: 1.4,
    },
    {
      type: "hill",
      label: "Kecik Tepe Ridge",
      points: [
        { x: 18, y: 28 },
        { x: 35, y: 24 },
        { x: 42, y: 31 },
        { x: 32, y: 40 },
        { x: 18, y: 37 },
      ],
    },
    {
      type: "hill",
      label: "Sari Tepe",
      points: [
        { x: 56, y: 16 },
        { x: 67, y: 14 },
        { x: 74, y: 21 },
        { x: 69, y: 29 },
        { x: 57, y: 27 },
      ],
    },
    {
      type: "forest",
      label: "Scrub Woodland",
      points: [
        { x: 7, y: 47 },
        { x: 16, y: 44 },
        { x: 22, y: 50 },
        { x: 18, y: 58 },
        { x: 8, y: 56 },
      ],
    },
    {
      type: "marsh",
      label: "Low Wet Ground",
      points: [
        { x: 66, y: 45 },
        { x: 79, y: 43 },
        { x: 84, y: 52 },
        { x: 76, y: 60 },
        { x: 65, y: 56 },
      ],
    },
    {
      type: "road",
      label: "Ankara Road",
      points: [
        { x: 46, y: 100 },
        { x: 45, y: 86 },
        { x: 45, y: 72 },
        { x: 46, y: 57 },
        { x: 47, y: 44 },
      ],
      width: 0.7,
    },
    {
      type: "urban",
      label: "Camp & Supply Park",
      points: [
        { x: 38, y: 82 },
        { x: 53, y: 82 },
        { x: 55, y: 90 },
        { x: 40, y: 92 },
      ],
    },
    {
      type: "fortification",
      label: "Wagon Barrier",
      points: [
        { x: 32, y: 63 },
        { x: 58, y: 63 },
        { x: 58, y: 67 },
        { x: 32, y: 67 },
      ],
    },
  ],

  forces: [
    {
      id: "otto-janissaries",
      name: "Janissary Core",
      side: 0,
      type: "infantry",
      count: 11000,
      commander: "Bayezid I",
      startPosition: { x: 45, y: 66 },
      color: "#8b3a3a",
    },
    {
      id: "otto-center-sipahi",
      name: "Center Sipahi",
      side: 0,
      type: "cavalry",
      count: 14000,
      commander: "Bayezid I",
      startPosition: { x: 45, y: 58 },
      color: "#8b3a3a",
    },
    {
      id: "otto-left-anatolian",
      name: "Anatolian Left Wing",
      side: 0,
      type: "cavalry",
      count: 18000,
      commander: "Suleyman Celebi",
      startPosition: { x: 26, y: 58 },
      color: "#8b3a3a",
    },
    {
      id: "otto-right-rumelian",
      name: "Rumelian Right Wing",
      side: 0,
      type: "cavalry",
      count: 16000,
      commander: "Musa Celebi",
      startPosition: { x: 62, y: 58 },
      color: "#8b3a3a",
    },
    {
      id: "otto-serb-guard",
      name: "Serbian Heavy Guard",
      side: 0,
      type: "cavalry",
      count: 5000,
      commander: "Stefan Lazarevic",
      startPosition: { x: 49, y: 72 },
      color: "#8b3a3a",
    },
    {
      id: "otto-archer-screen",
      name: "Ottoman Archer Screen",
      side: 0,
      type: "archers",
      count: 9000,
      commander: "Ottoman Emirs",
      startPosition: { x: 45, y: 52 },
      color: "#8b3a3a",
    },
    {
      id: "otto-tatar-aux",
      name: "Tatar Auxiliaries",
      side: 0,
      type: "cavalry",
      count: 9000,
      commander: "Auxiliary Beys",
      startPosition: { x: 33, y: 53 },
      color: "#8b3a3a",
    },

    {
      id: "tim-center-guard",
      name: "Timurid Center Guard",
      side: 1,
      type: "infantry",
      count: 26000,
      commander: "Timur",
      startPosition: { x: 45, y: 34 },
      color: "#3a5a8b",
    },
    {
      id: "tim-left-cav",
      name: "Timurid Left Cavalry",
      side: 1,
      type: "cavalry",
      count: 25000,
      commander: "Shah Rukh",
      startPosition: { x: 24, y: 32 },
      color: "#3a5a8b",
    },
    {
      id: "tim-right-cav",
      name: "Timurid Right Cavalry",
      side: 1,
      type: "cavalry",
      count: 25000,
      commander: "Miran Shah",
      startPosition: { x: 63, y: 32 },
      color: "#3a5a8b",
    },
    {
      id: "tim-horse-archers",
      name: "Horse Archer Mass",
      side: 1,
      type: "archers",
      count: 22000,
      commander: "Timurid Emirs",
      startPosition: { x: 42, y: 38 },
      color: "#3a5a8b",
    },
    {
      id: "tim-elephants",
      name: "Elephant Shock Group",
      side: 1,
      type: "elephants",
      count: 32,
      commander: "Timur",
      startPosition: { x: 47, y: 28 },
      color: "#3a5a8b",
    },
    {
      id: "tim-reserve",
      name: "Timurid Reserve",
      side: 1,
      type: "cavalry",
      count: 28000,
      commander: "Khalil Sultan",
      startPosition: { x: 46, y: 20 },
      color: "#3a5a8b",
    },
  ],

  phases: [
    {
      title: "Contact on a Prepared Battlefield",
      timestamp: "Early morning",
      duration: "~1 hour",
      narration:
        "Both armies deploy across the Cubuk plain with Timur already holding the better water and fresher cavalry reserve. Ottoman troops are fatigued from forced marching and line up in a deep center with cavalry wings.",
      movements: [
        {
          unitId: "tim-horse-archers",
          from: { x: 42, y: 38 },
          to: { x: 43, y: 42 },
          action: "bombard",
          significant: true,
          note: "Timurid horse archers begin sustained opening volleys.",
        },
        {
          unitId: "otto-archer-screen",
          from: { x: 45, y: 52 },
          to: { x: 45, y: 50 },
          action: "bombard",
          note: "Ottoman screen answers with counter-volley fire.",
        },
        {
          unitId: "tim-elephants",
          from: { x: 47, y: 28 },
          to: { x: 47, y: 33 },
          action: "advance",
          significant: true,
          note: "Elephants move up to pressure the Ottoman center line.",
        },
      ],
      casualties: {
        side0: 1400,
        side1: 900,
        description: "Ranged attrition and early skirmish losses",
      },
      tacticalNote: "Timur opens with standoff pressure to stretch Ottoman cohesion before committing reserve cavalry.",
    },
    {
      title: "Wing Probing and Compression",
      timestamp: "Mid-morning",
      duration: "~1 hour",
      narration:
        "Timurid cavalry probes both Ottoman wings while horse archers keep center pressure constant. Ottoman right holds initially, but the left wing begins to lose alignment under repeated harassment.",
      movements: [
        {
          unitId: "tim-left-cav",
          from: { x: 24, y: 32 },
          to: { x: 20, y: 43 },
          curve: { control: { x: 18, y: 37 } },
          action: "flank",
          significant: true,
          note: "Timurid left attempts to roll Ottoman left edge.",
        },
        {
          unitId: "tim-right-cav",
          from: { x: 63, y: 32 },
          to: { x: 67, y: 43 },
          curve: { control: { x: 70, y: 37 } },
          action: "flank",
          note: "Timurid right widens to threaten a two-sided envelope.",
        },
        {
          unitId: "otto-left-anatolian",
          from: { x: 26, y: 58 },
          to: { x: 24, y: 54 },
          action: "retreat",
          note: "Anatolian line gives ground under sustained pressure.",
        },
      ],
      casualties: {
        side0: 2200,
        side1: 1200,
        description: "Wing skirmishing and attritional cavalry losses",
      },
      tacticalNote: "The Timurid objective is positional: bend both Ottoman wings before decisive commitment.",
    },
    {
      title: "Anatolian Defections",
      timestamp: "Late morning",
      duration: "~45 minutes",
      narration:
        "Political warfare becomes operational effect: major Anatolian and Tatar elements defect during contact. Bayezid's left side loses mass and command coherence within minutes, exposing the Ottoman center.",
      movements: [
        {
          unitId: "otto-left-anatolian",
          from: { x: 24, y: 54 },
          to: { x: 17, y: 41 },
          curve: { control: { x: 19, y: 48 } },
          action: "defect",
          toSide: 1,
          significant: true,
          note: "Large Anatolian contingents defect to Timur's side.",
        },
        {
          unitId: "otto-tatar-aux",
          from: { x: 33, y: 53 },
          to: { x: 22, y: 39 },
          curve: { control: { x: 28, y: 44 } },
          action: "defect",
          toSide: 1,
          significant: true,
          note: "Tatar auxiliaries switch allegiance mid-battle.",
        },
        {
          unitId: "tim-left-cav",
          from: { x: 20, y: 43 },
          to: { x: 27, y: 51 },
          action: "advance",
        },
      ],
      casualties: {
        side0: 3500,
        side1: 600,
        description: "Limited direct losses, catastrophic Ottoman force loss through defection",
      },
      tacticalNote: "Defection converts strategic preparation into immediate tactical collapse on Bayezid's left.",
    },
    {
      title: "Center Isolation",
      timestamp: "Noon",
      duration: "~1 hour",
      narration:
        "With flank integrity broken, Timur drives converging attacks into the Ottoman center corridor. Bayezid's elite infantry and guard cavalry are forced into a compressed defensive pocket near the wagon barrier.",
      movements: [
        {
          unitId: "tim-center-guard",
          from: { x: 45, y: 34 },
          to: { x: 45, y: 46 },
          action: "advance",
          significant: true,
          note: "Timurid center pushes directly into the Ottoman core.",
        },
        {
          unitId: "tim-right-cav",
          from: { x: 67, y: 43 },
          to: { x: 60, y: 56 },
          curve: { control: { x: 64, y: 50 } },
          action: "encircle",
          significant: true,
          note: "Right-wing cavalry closes Ottoman escape lanes.",
        },
        {
          unitId: "otto-right-rumelian",
          from: { x: 62, y: 58 },
          to: { x: 72, y: 71 },
          action: "rout",
          damage: "heavy",
          note: "Rumelian cavalry line disintegrates under converging attacks.",
        },
      ],
      casualties: {
        side0: 9000,
        side1: 2600,
        description: "Heavy center fighting and collapse of Ottoman right coherence",
      },
      tacticalNote: "Timur uses synchronized pressure, not one shock blow, to isolate Bayezid's command group.",
    },
    {
      title: "Janissary and Serbian Last Stand",
      timestamp: "Early afternoon",
      duration: "~90 minutes",
      narration:
        "The Janissaries and Serbian heavy cavalry form a compact final resistance around Bayezid. They inflict sharp local losses, but Timurid reserves feed in fresh cavalry from depth and continue tightening the ring.",
      movements: [
        {
          unitId: "otto-janissaries",
          from: { x: 45, y: 66 },
          to: { x: 43, y: 64 },
          action: "hold",
          significant: true,
          note: "Janissary line locks into static defensive formation.",
        },
        {
          unitId: "otto-serb-guard",
          from: { x: 49, y: 72 },
          to: { x: 47, y: 68 },
          curve: { control: { x: 45, y: 71 } },
          action: "charge",
          significant: true,
          note: "Serbian guard launches repeated counter-charges.",
        },
        {
          unitId: "tim-reserve",
          from: { x: 46, y: 20 },
          to: { x: 49, y: 49 },
          action: "advance",
          significant: true,
          note: "Timurid reserve commits to seal the encirclement.",
        },
      ],
      casualties: {
        side0: 12000,
        side1: 5200,
        description: "Very high close-combat losses in the central pocket",
      },
      tacticalNote: "Operational depth decides the phase: Timur can rotate fresh cavalry while Bayezid cannot reconstitute a line.",
    },
    {
      title: "Collapse and Capture",
      timestamp: "Late afternoon",
      duration: "~1 hour",
      narration:
        "Final Ottoman resistance breaks. Parts of the Serbian contingent carve out and withdraw, but the Janissary core is destroyed and Bayezid is captured during the collapse of the center pocket.",
      movements: [
        {
          unitId: "otto-serb-guard",
          from: { x: 47, y: 68 },
          to: { x: 60, y: 83 },
          action: "retreat",
          note: "Serbian heavy cavalry executes fighting withdrawal.",
        },
        {
          unitId: "otto-janissaries",
          from: { x: 43, y: 64 },
          to: { x: 43, y: 65 },
          action: "hold",
          damage: "eliminated",
          significant: true,
          note: "Janissary core is overrun and destroyed in place.",
        },
        {
          unitId: "tim-center-guard",
          from: { x: 45, y: 46 },
          to: { x: 44, y: 60 },
          action: "advance",
          significant: true,
          note: "Timurid center overruns Bayezid's final position.",
        },
      ],
      casualties: {
        side0: 15000,
        side1: 3000,
        description: "Terminal losses as Ottoman center collapses and command is captured",
      },
      tacticalNote: "Capture of the ruler turns battlefield defeat into immediate strategic dislocation.",
    },
  ],

  aftermath: {
    outcome:
      "Timurid strategic victory. Bayezid I was captured, Ottoman field army shattered, and imperial succession destabilized.",
    casualties: {
      side0: {
        dead: 42000,
        wounded: 15000,
        captured: 22000,
      },
      side1: {
        dead: 14500,
        wounded: 9800,
        captured: 0,
      },
    },
    significance:
      "Ankara halted Ottoman expansion for a generation and triggered the Ottoman Interregnum (1402-1413), an internal civil conflict among Bayezid's heirs. Timur's campaign showed how political preparation, logistics, and battlefield maneuver could decisively defeat a powerful centralized army. The battle delayed Ottoman pressure on Constantinople and reshaped power balances across Anatolia and the eastern Mediterranean.",
  },
};
