import { BattleData } from "./types";

export const barbarossaData: BattleData = {
  battleMetadata: {
    name: "Operation Barbarossa",
    date: "22 June - December 1941",
    location: "From the German-Soviet frontier toward Leningrad, Moscow, and Ukraine",
    belligerents: ["Nazi Germany and Axis allies", "Soviet Union"],
    commanders: [
      ["Adolf Hitler", "Fedor von Bock", "Wilhelm von Leeb", "Gerd von Rundstedt", "Heinz Guderian", "Erich Hoepner"],
      ["Joseph Stalin", "Georgy Zhukov", "Semyon Timoshenko", "Semyon Budyonny", "Ivan Konev"],
    ],
    outcome: "Initial massive Axis advances, but strategic failure to defeat the Soviet Union in 1941",
    scale: "Largest land invasion in history: ~3 million Axis troops vs multi-million Soviet forces",
    environment: "temperate",
  },

  context:
    "Operation Barbarossa began on 22 June 1941 as the German-led Axis invasion of the Soviet Union along a vast front. The campaign opened with large armored spearheads driving deep penetrations while infantry armies followed to reduce pockets. German planning sought rapid destruction of Soviet field forces before logistical strain, weather, and Soviet mobilization could reverse momentum.\\n\\nThe invasion unfolded across three main strategic axes: Army Group North toward Leningrad, Army Group Center toward Moscow, and Army Group South toward Ukraine. Early encirclements at Bialystok-Minsk and Smolensk inflicted huge Soviet losses, but Soviet command gradually rebuilt defensive depth and replaced shattered formations at a scale Germany had not fully anticipated.\\n\\nAs summer turned to autumn, widening distances, attrition, and transport bottlenecks weakened German operational tempo. The decision to divert armored strength south delayed the final Moscow thrust. By winter, Soviet reserves and counteroffensives halted and reversed German advances, ending hopes of a short campaign.",

  terrain: [
    {
      type: "forest",
      label: "Baltic Forest Belt",
      points: [
        { x: 10, y: 12 },
        { x: 30, y: 10 },
        { x: 36, y: 20 },
        { x: 24, y: 30 },
        { x: 11, y: 25 },
      ],
    },
    {
      type: "marsh",
      label: "Pripyat Marshes",
      points: [
        { x: 38, y: 38 },
        { x: 58, y: 36 },
        { x: 64, y: 48 },
        { x: 56, y: 60 },
        { x: 40, y: 56 },
      ],
    },
    {
      type: "forest",
      label: "Smolensk-Moscow Forest Zones",
      points: [
        { x: 62, y: 18 },
        { x: 84, y: 16 },
        { x: 88, y: 28 },
        { x: 76, y: 36 },
        { x: 63, y: 30 },
      ],
    },
    {
      type: "river",
      label: "Dvina-Dnieper Line",
      points: [
        { x: 28, y: 0 },
        { x: 34, y: 10 },
        { x: 40, y: 20 },
        { x: 42, y: 32 },
        { x: 46, y: 44 },
        { x: 52, y: 58 },
        { x: 60, y: 74 },
        { x: 70, y: 100 },
      ],
      width: 1.2,
    },
    {
      type: "river",
      label: "Volkhov-Luga Defensive Waters",
      points: [
        { x: 8, y: 0 },
        { x: 12, y: 12 },
        { x: 14, y: 24 },
        { x: 13, y: 36 },
        { x: 10, y: 48 },
        { x: 8, y: 62 },
      ],
      width: 1,
    },
    {
      type: "road",
      label: "Minsk-Smolensk-Moscow Axis",
      points: [
        { x: 18, y: 52 },
        { x: 30, y: 46 },
        { x: 44, y: 40 },
        { x: 58, y: 34 },
        { x: 72, y: 28 },
        { x: 86, y: 24 },
      ],
      width: 0.8,
    },
    {
      type: "road",
      label: "Kiev-Dnieper Axis",
      points: [
        { x: 30, y: 76 },
        { x: 42, y: 70 },
        { x: 56, y: 66 },
        { x: 70, y: 64 },
        { x: 84, y: 62 },
      ],
      width: 0.75,
    },
    {
      type: "urban",
      label: "Minsk",
      points: [
        { x: 27, y: 45 },
        { x: 32, y: 45 },
        { x: 33, y: 50 },
        { x: 27, y: 50 },
      ],
    },
    {
      type: "urban",
      label: "Smolensk",
      points: [
        { x: 53, y: 34 },
        { x: 58, y: 34 },
        { x: 59, y: 39 },
        { x: 53, y: 39 },
      ],
    },
    {
      type: "urban",
      label: "Kiev",
      points: [
        { x: 62, y: 62 },
        { x: 67, y: 62 },
        { x: 68, y: 67 },
        { x: 62, y: 67 },
      ],
    },
    {
      type: "urban",
      label: "Moscow Approaches",
      points: [
        { x: 84, y: 20 },
        { x: 91, y: 20 },
        { x: 92, y: 27 },
        { x: 84, y: 27 },
      ],
    },
    {
      type: "snow",
      label: "Winter Front",
      points: [
        { x: 70, y: 9 },
        { x: 82, y: 7 },
        { x: 94, y: 9 },
        { x: 100, y: 13 },
        { x: 100, y: 22 },
        { x: 96, y: 31 },
        { x: 88, y: 38 },
        { x: 79, y: 40 },
        { x: 73, y: 36 },
        { x: 69, y: 27 },
        { x: 68, y: 18 },
      ],
    },
  ],

  forces: [
    {
      id: "axis-ag-north",
      name: "Army Group North",
      side: 0,
      type: "infantry",
      count: 700000,
      commander: "Wilhelm von Leeb",
      startPosition: { x: 12, y: 22 },
      color: "#8b3a3a",
    },
    {
      id: "axis-ag-center-infantry",
      name: "Army Group Center Infantry Armies",
      side: 0,
      type: "infantry",
      count: 1300000,
      commander: "Fedor von Bock",
      startPosition: { x: 16, y: 50 },
      color: "#8b3a3a",
    },
    {
      id: "axis-ag-center-panzer",
      name: "Army Group Center Panzer Groups",
      side: 0,
      type: "tanks",
      count: 1700,
      commander: "Guderian and Hoepner",
      startPosition: { x: 18, y: 46 },
      color: "#8b3a3a",
    },
    {
      id: "axis-ag-south",
      name: "Army Group South",
      side: 0,
      type: "infantry",
      count: 1050000,
      commander: "Gerd von Rundstedt",
      startPosition: { x: 20, y: 78 },
      color: "#8b3a3a",
    },
    {
      id: "axis-luftwaffe",
      name: "Luftwaffe Eastern Air Fleets",
      side: 0,
      type: "aircraft",
      count: 2000,
      commander: "Kesselring and Lohr",
      startPosition: { x: 18, y: 58 },
      color: "#8b3a3a",
    },

    {
      id: "sov-western-front",
      name: "Soviet Western Front",
      side: 1,
      type: "infantry",
      count: 1100000,
      commander: "Dmitry Pavlov (early), successors",
      startPosition: { x: 34, y: 50 },
      color: "#3a5a8b",
    },
    {
      id: "sov-reserve-front",
      name: "Soviet Reserve Front Formations",
      side: 1,
      type: "infantry",
      count: 900000,
      commander: "Timoshenko and Zhukov staff",
      startPosition: { x: 58, y: 36 },
      color: "#3a5a8b",
    },
    {
      id: "sov-southwest-front",
      name: "Soviet Southwestern Front",
      side: 1,
      type: "infantry",
      count: 1200000,
      commander: "Budyonny / Kirponos",
      startPosition: { x: 54, y: 70 },
      color: "#3a5a8b",
    },
    {
      id: "sov-armored-reserve",
      name: "Soviet Armored Counterattack Groups",
      side: 1,
      type: "tanks",
      count: 2200,
      commander: "Front armored commanders",
      startPosition: { x: 46, y: 56 },
      color: "#3a5a8b",
    },
    {
      id: "sov-air-forces",
      name: "Soviet VVS Front Aviation",
      side: 1,
      type: "aircraft",
      count: 1800,
      commander: "VVS district commands",
      startPosition: { x: 48, y: 60 },
      color: "#3a5a8b",
    },
  ],

  phases: [
    {
      title: "Invasion Shock: Frontier Breakthroughs",
      timestamp: "22-28 June 1941",
      duration: "~1 week",
      narration:
        "Axis forces launch a full-front surprise assault with massive artillery and air strikes. Panzer spearheads rupture forward Soviet lines while infantry armies widen breaches. Soviet command suffers severe disruption in the opening days.",
      movements: [
        {
          unitId: "axis-ag-center-panzer",
          from: { x: 18, y: 46 },
          to: { x: 30, y: 44 },
          action: "advance",
          significant: true,
          note: "Panzer thrust drives deep between Soviet frontier armies.",
        },
        {
          unitId: "axis-luftwaffe",
          from: { x: 18, y: 58 },
          to: { x: 28, y: 52 },
          action: "bombard",
          significant: true,
          note: "Air strikes target Soviet airfields and communications.",
        },
        {
          unitId: "sov-western-front",
          from: { x: 34, y: 50 },
          to: { x: 38, y: 52 },
          action: "retreat",
          damage: "heavy",
          note: "Forward defenses collapse in multiple sectors.",
        },
      ],
      casualties: { side0: 45000, side1: 320000, description: "Massive Soviet losses and captures in opening battles" },
      tacticalNote: "Operational surprise plus air-ground integration creates disproportionate early dislocation.",
    },
    {
      title: "Bialystok-Minsk Encirclement",
      timestamp: "Late June - Early July",
      duration: "~10 days",
      narration:
        "Army Group Center panzer groups close large encirclement pockets west of Minsk. Soviet attempts to break out are fragmented and costly. Axis command secures one of the largest early operational victories of the campaign.",
      movements: [
        {
          unitId: "axis-ag-center-panzer",
          from: { x: 30, y: 44 },
          to: { x: 38, y: 42 },
          action: "encircle",
          significant: true,
          note: "Panzer jaws close behind Soviet forward concentrations.",
        },
        {
          unitId: "axis-ag-center-infantry",
          from: { x: 16, y: 50 },
          to: { x: 30, y: 48 },
          action: "advance",
          note: "Infantry armies reduce and seal encircled pockets.",
        },
        {
          unitId: "sov-armored-reserve",
          from: { x: 46, y: 56 },
          to: { x: 40, y: 52 },
          action: "charge",
          note: "Counterattacks fail to reopen corridor.",
        },
      ],
      casualties: { side0: 60000, side1: 420000, description: "Large Soviet pocket losses around Minsk" },
      tacticalNote: "Fast armor plus follow-on infantry turns penetration into operational annihilation.",
    },
    {
      title: "Axis North and South Expand Front Gains",
      timestamp: "July 1941",
      duration: "~3 weeks",
      narration:
        "Army Group North advances toward Leningrad approaches while Army Group South fights through western Ukraine. Soviet forces trade space for time, attempting to rebuild command structures. Logistics begin to stretch Axis operational rhythm.",
      movements: [
        {
          unitId: "axis-ag-north",
          from: { x: 12, y: 22 },
          to: { x: 22, y: 20 },
          action: "advance",
          significant: true,
          note: "Northern push presses toward Luga defensive line.",
        },
        {
          unitId: "axis-ag-south",
          from: { x: 20, y: 78 },
          to: { x: 34, y: 74 },
          action: "advance",
          note: "Southern armies force retreats in western Ukraine.",
        },
        {
          unitId: "sov-southwest-front",
          from: { x: 54, y: 70 },
          to: { x: 60, y: 70 },
          action: "retreat",
          note: "Southwestern Front conducts delaying withdrawals.",
        },
      ],
      casualties: { side0: 90000, side1: 260000, description: "High attrition across widening fronts" },
      tacticalNote: "Broad-front offensives dilute operational focus as distance and supply friction grow.",
    },
    {
      title: "Smolensk Battle and Soviet Reconstitution",
      timestamp: "July-August 1941",
      duration: "~6 weeks",
      narration:
        "German spearheads reach Smolensk and fight intense battles against newly assembled Soviet reserves. Encirclements still occur, but Soviet resistance grows stiffer and more organized. Tempo slows compared with June advances.",
      movements: [
        {
          unitId: "axis-ag-center-panzer",
          from: { x: 38, y: 42 },
          to: { x: 54, y: 36 },
          action: "advance",
          significant: true,
          note: "Panzer groups drive to Smolensk axis.",
        },
        {
          unitId: "sov-reserve-front",
          from: { x: 58, y: 36 },
          to: { x: 54, y: 38 },
          action: "hold",
          significant: true,
          note: "Reserve Front contests Smolensk approaches.",
        },
        {
          unitId: "sov-air-forces",
          from: { x: 48, y: 60 },
          to: { x: 56, y: 44 },
          action: "bombard",
          note: "Soviet sorties support counterattacks near Smolensk.",
        },
      ],
      casualties: { side0: 140000, side1: 380000, description: "Brutal attritional battle with repeated local reversals" },
      tacticalNote: "Defender regeneration can convert a blitz tempo campaign into attritional struggle.",
    },
    {
      title: "Strategic Divergence: Moscow vs Ukraine",
      timestamp: "August 1941",
      duration: "~3 weeks",
      narration:
        "German high command debates strategic priority between direct Moscow thrust and southern encirclement opportunities. Armored assets are redirected, reducing immediate pressure on Moscow axis. Soviet command gains time to deepen central defenses.",
      movements: [
        {
          unitId: "axis-ag-center-panzer",
          from: { x: 54, y: 36 },
          to: { x: 56, y: 50 },
          action: "flank",
          significant: true,
          note: "Key armor shifts southward for encirclement operations.",
        },
        {
          unitId: "axis-ag-south",
          from: { x: 34, y: 74 },
          to: { x: 50, y: 70 },
          action: "advance",
          note: "Southern armies prepare major pincer against Kiev sector.",
        },
        {
          unitId: "sov-reserve-front",
          from: { x: 54, y: 38 },
          to: { x: 62, y: 34 },
          action: "hold",
          note: "Soviets fortify central direction while pressure eases briefly.",
        },
      ],
      casualties: { side0: 50000, side1: 80000, description: "Operational repositioning with heavy local fighting" },
      tacticalNote: "Strategic retasking of mobile forces can win theaters while sacrificing campaign tempo.",
    },
    {
      title: "Kiev Encirclement Catastrophe",
      timestamp: "September 1941",
      duration: "~1 month",
      narration:
        "A giant pincer around Kiev traps major Soviet Southwestern Front formations. Axis forces secure one of history's largest encirclement victories. Soviet losses are immense, but the operation consumes time before final Moscow drive.",
      movements: [
        {
          unitId: "axis-ag-center-panzer",
          from: { x: 56, y: 50 },
          to: { x: 66, y: 64 },
          action: "encircle",
          significant: true,
          note: "Southward panzer drive closes on Kiev rear.",
        },
        {
          unitId: "axis-ag-south",
          from: { x: 50, y: 70 },
          to: { x: 62, y: 66 },
          action: "encircle",
          significant: true,
          note: "Army Group South links pincers around Soviet forces.",
        },
        {
          unitId: "sov-southwest-front",
          from: { x: 60, y: 70 },
          to: { x: 66, y: 68 },
          action: "rout",
          damage: "heavy",
          significant: true,
          note: "Southwestern Front collapses inside encirclement.",
        },
      ],
      casualties: { side0: 120000, side1: 600000, description: "Massive Soviet capture/losses in Kiev pocket" },
      tacticalNote: "Huge tactical success can still undermine strategic timing if it delays the decisive axis.",
    },
    {
      title: "Operation Typhoon Begins",
      timestamp: "Late September - October 1941",
      duration: "~3 weeks",
      narration:
        "Axis forces launch final major offensive toward Moscow. Early breakthroughs at Vyazma and Bryansk create additional Soviet encirclements. Yet weather deterioration and road collapse begin to erode offensive mobility.",
      movements: [
        {
          unitId: "axis-ag-center-panzer",
          from: { x: 66, y: 64 },
          to: { x: 70, y: 34 },
          action: "advance",
          significant: true,
          note: "Panzer groups reorient and surge on Moscow axis.",
        },
        {
          unitId: "axis-ag-center-infantry",
          from: { x: 30, y: 48 },
          to: { x: 52, y: 40 },
          action: "advance",
          note: "Infantry follows to reduce new encirclement pockets.",
        },
        {
          unitId: "sov-western-front",
          from: { x: 38, y: 52 },
          to: { x: 56, y: 44 },
          action: "retreat",
          damage: "heavy",
          note: "Soviet front falls back under renewed pressure.",
        },
      ],
      casualties: { side0: 170000, side1: 500000, description: "Major Soviet losses at Vyazma-Bryansk; Axis attrition rises" },
      tacticalNote: "Late-campaign offensives require logistics to match operational ambition.",
    },
    {
      title: "Rasputitsa and Operational Stall",
      timestamp: "October-November 1941",
      duration: "~5 weeks",
      narration:
        "Autumn mud turns roads into quagmires, severely reducing Axis mobility and supply throughput. Soviet defense lines thicken closer to Moscow with fresh formations. Local gains continue but at much lower speed and higher cost.",
      movements: [
        {
          unitId: "axis-ag-center-panzer",
          from: { x: 70, y: 34 },
          to: { x: 76, y: 30 },
          action: "hold",
          significant: true,
          note: "Armor slowed by mud, mechanical wear, and fuel strain.",
        },
        {
          unitId: "sov-reserve-front",
          from: { x: 62, y: 34 },
          to: { x: 74, y: 30 },
          action: "advance",
          note: "Soviet reserves reinforce Mozhaisk-Moscow belt.",
        },
        {
          unitId: "axis-luftwaffe",
          from: { x: 28, y: 52 },
          to: { x: 72, y: 32 },
          action: "bombard",
          note: "Air support attempts to compensate for ground friction.",
        },
      ],
      casualties: { side0: 130000, side1: 210000, description: "Attrition-heavy stalling phase with reduced maneuver" },
      tacticalNote: "Terrain-season effects can nullify nominal maneuver superiority.",
    },
    {
      title: "Moscow Near-Reach, Then Exhaustion",
      timestamp: "Late November 1941",
      duration: "~2 weeks",
      narration:
        "German forward units approach outer Moscow defensive zones but are exhausted and undersupplied. Soviet defenses, reserves, and urban-depth preparation hold. The offensive culminates without decisive breakthrough.",
      movements: [
        {
          unitId: "axis-ag-center-infantry",
          from: { x: 52, y: 40 },
          to: { x: 78, y: 28 },
          action: "advance",
          significant: true,
          note: "Final sustained push toward Moscow approaches.",
        },
        {
          unitId: "axis-ag-center-panzer",
          from: { x: 76, y: 30 },
          to: { x: 82, y: 26 },
          action: "advance",
          note: "Panzer elements reach near-culmination positions.",
        },
        {
          unitId: "sov-reserve-front",
          from: { x: 74, y: 30 },
          to: { x: 82, y: 26 },
          action: "hold",
          significant: true,
          note: "Soviet defensive depth prevents breakthrough.",
        },
      ],
      casualties: { side0: 90000, side1: 150000, description: "High losses in final approach battles" },
      tacticalNote: "Culmination occurs when combat power and supply can no longer sustain offensive intent.",
    },
    {
      title: "Soviet Winter Counteroffensive",
      timestamp: "December 1941",
      duration: "~3 weeks",
      narration:
        "With fresh Siberian and reserve formations, the Soviets launch broad counterattacks before Moscow. German lines are pushed back from advanced positions, ending any prospect of quick victory. Barbarossa's strategic objective fails in 1941.",
      movements: [
        {
          unitId: "sov-reserve-front",
          from: { x: 82, y: 26 },
          to: { x: 72, y: 30 },
          action: "advance",
          significant: true,
          note: "Soviet counteroffensive forces German pullback.",
        },
        {
          unitId: "axis-ag-center-infantry",
          from: { x: 78, y: 28 },
          to: { x: 66, y: 34 },
          action: "retreat",
          damage: "heavy",
          significant: true,
          note: "German infantry withdraws to winter defensive lines.",
        },
        {
          unitId: "axis-ag-center-panzer",
          from: { x: 82, y: 26 },
          to: { x: 70, y: 32 },
          action: "retreat",
          note: "Panzer forces disengage under cold-weather stress.",
        },
      ],
      casualties: { side0: 180000, side1: 210000, description: "Severe winter combat losses on both sides" },
      tacticalNote: "Strategic endurance, reserve depth, and timing of counteroffense can overturn early campaign shock.",
    },
  ],

  aftermath: {
    outcome:
      "Axis forces failed to destroy Soviet capacity to continue the war in 1941; front stabilized after Soviet winter offensives.",
    casualties: {
      side0: { dead: 350000, wounded: 750000, captured: 20000 },
      side1: { dead: 900000, wounded: 1500000, captured: 3000000 },
    },
    significance:
      "Barbarossa transformed World War II into a prolonged total war of attrition on the Eastern Front. It exposed limits of blitzkrieg against continental depth, industrial mobilization, and seasonal logistics constraints, setting conditions for the long strategic reversal that culminated in Axis defeat.",
  },
};
