import { BattleData } from "./types";

export const grandSlamData: BattleData = {
  battleMetadata: {
    name: "Operation Grand Slam",
    date: "1-6 September 1965",
    location: "Chhamb-Jaurian-Akhnoor axis, Jammu region",
    belligerents: ["Pakistan", "India"],
    commanders: [
      ["Maj Gen Akhtar Hussain Malik", "Maj Gen Yahya Khan", "Pakistan 12 Division officers"],
      ["Maj Gen H. S. Katoch", "Western Command field officers", "Indian armored and infantry commanders"],
    ],
    outcome: "Pakistani tactical gains at Chhamb and Jaurian, but advance stalled before Akhnoor",
    scale: "Corps-level pressure with armored, infantry, and artillery groupings on both sides",
    environment: "temperate",
  },

  context:
    "Operation Grand Slam opened in early September 1965 as Pakistan's major thrust on the Chhamb-Jaurian-Akhnoor line. The operational idea was to break through Indian forward defenses west of the Manawar Tawi, seize crossings, and threaten Akhnoor, a key road and bridge node linking Indian positions in Jammu and the wider Kashmir theater.\\n\\nInitial Pakistani attacks used concentrated artillery, armor-infantry teams, and maneuver along roads and cultivable corridors between river obstacles and low hill country. Indian forward elements fought delaying actions while attempting to stabilize successive defensive lines eastward.\\n\\nA major command transition during the operation, together with growing Indian reinforcement and intense artillery duels, reduced offensive momentum. Pakistan secured important tactical ground in the opening days, but the drive did not convert into capture of Akhnoor before the campaign widened across the international border.",

  terrain: [
    {
      type: "ridge",
      label: "Pir Panjal Foothill Belt",
      points: [
        { x: 0, y: 0 },
        { x: 24, y: 2 },
        { x: 20, y: 24 },
        { x: 16, y: 51 },
        { x: 19, y: 77 },
        { x: 23, y: 99 },
        { x: 0, y: 100 },
      ],
    },
    {
      type: "river",
      label: "Manawar Tawi",
      points: [
        { x: 36, y: 0 },
        { x: 35, y: 13 },
        { x: 38, y: 26 },
        { x: 41, y: 39 },
        { x: 39, y: 52 },
        { x: 36, y: 67 },
        { x: 37, y: 82 },
        { x: 35, y: 100 },
      ],
      width: 1.5,
    },
    {
      type: "river",
      label: "Akhnoor River Corridor",
      points: [
        { x: 73, y: 0 },
        { x: 72, y: 16 },
        { x: 74, y: 31 },
        { x: 75, y: 49 },
        { x: 73, y: 66 },
        { x: 71, y: 84 },
        { x: 72, y: 100 },
      ],
      width: 1.2,
    },
    {
      type: "hill",
      label: "Akhnoor Heights",
      points: [
        { x: 62, y: 43 },
        { x: 70, y: 41 },
        { x: 76, y: 47 },
        { x: 71, y: 54 },
        { x: 63, y: 52 },
      ],
    },
    {
      type: "marsh",
      label: "Seasonal Nullah Ground",
      points: [
        { x: 42, y: 41 },
        { x: 57, y: 38 },
        { x: 63, y: 47 },
        { x: 58, y: 58 },
        { x: 44, y: 56 },
      ],
    },
    {
      type: "forest",
      label: "Orchard and Scrub Belt",
      points: [
        { x: 23, y: 59 },
        { x: 34, y: 56 },
        { x: 39, y: 64 },
        { x: 32, y: 73 },
        { x: 21, y: 70 },
      ],
    },
    {
      type: "road",
      label: "Chhamb-Jaurian-Akhnoor Road",
      points: [
        { x: 16, y: 54 },
        { x: 30, y: 54 },
        { x: 44, y: 54 },
        { x: 58, y: 55 },
        { x: 72, y: 56 },
      ],
      width: 1,
    },
    {
      type: "road",
      label: "Lateral Supply Route",
      points: [
        { x: 24, y: 100 },
        { x: 30, y: 83 },
        { x: 34, y: 68 },
        { x: 39, y: 53 },
        { x: 45, y: 35 },
      ],
      width: 0.7,
    },
    {
      type: "urban",
      label: "Chhamb",
      points: [
        { x: 18, y: 49 },
        { x: 25, y: 49 },
        { x: 26, y: 56 },
        { x: 18, y: 56 },
      ],
    },
    {
      type: "urban",
      label: "Jaurian",
      points: [
        { x: 46, y: 50 },
        { x: 53, y: 50 },
        { x: 54, y: 58 },
        { x: 46, y: 58 },
      ],
    },
    {
      type: "urban",
      label: "Akhnoor Bridgehead",
      points: [
        { x: 70, y: 50 },
        { x: 77, y: 50 },
        { x: 78, y: 58 },
        { x: 70, y: 58 },
      ],
    },
    {
      type: "fortification",
      label: "Indian Forward Defensive Belt",
      points: [
        { x: 26, y: 60 },
        { x: 44, y: 60 },
        { x: 44, y: 64 },
        { x: 26, y: 64 },
      ],
    },
    {
      type: "fortification",
      label: "Akhnoor Blocking Line",
      points: [
        { x: 58, y: 62 },
        { x: 76, y: 62 },
        { x: 76, y: 66 },
        { x: 58, y: 66 },
      ],
    },
  ],

  forces: [
    {
      id: "pak-main-infantry",
      name: "Pakistani Main Infantry",
      side: 0,
      type: "infantry",
      count: 16000,
      commander: "Akhtar Hussain Malik",
      startPosition: { x: 18, y: 68 },
      color: "#8b3a3a",
    },
    {
      id: "pak-armored-group",
      name: "Pakistani Armored Group",
      side: 0,
      type: "tanks",
      count: 180,
      commander: "Armored brigade command",
      startPosition: { x: 15, y: 58 },
      color: "#8b3a3a",
    },
    {
      id: "pak-artillery",
      name: "Pakistani Artillery Concentration",
      side: 0,
      type: "artillery",
      count: 96,
      commander: "Corps artillery staff",
      startPosition: { x: 12, y: 74 },
      color: "#8b3a3a",
    },
    {
      id: "pak-left-flank",
      name: "Pakistani Left Flank Brigade",
      side: 0,
      type: "infantry",
      count: 7000,
      commander: "Forward brigade command",
      startPosition: { x: 11, y: 46 },
      color: "#8b3a3a",
    },
    {
      id: "pak-right-flank",
      name: "Pakistani Right Flank Group",
      side: 0,
      type: "infantry",
      count: 6500,
      commander: "Right sector command",
      startPosition: { x: 24, y: 84 },
      color: "#8b3a3a",
    },

    {
      id: "ind-forward-infantry",
      name: "Indian Forward Infantry",
      side: 1,
      type: "infantry",
      count: 14000,
      commander: "H. S. Katoch",
      startPosition: { x: 34, y: 60 },
      color: "#3a5a8b",
    },
    {
      id: "ind-armor-screen",
      name: "Indian Armor Screen",
      side: 1,
      type: "tanks",
      count: 120,
      commander: "Indian armored commanders",
      startPosition: { x: 43, y: 55 },
      color: "#3a5a8b",
    },
    {
      id: "ind-jaurian-line",
      name: "Jaurian Defensive Group",
      side: 1,
      type: "infantry",
      count: 9000,
      commander: "Jaurian sector HQ",
      startPosition: { x: 52, y: 62 },
      color: "#3a5a8b",
    },
    {
      id: "ind-akhnoor-reserve",
      name: "Akhnoor Reserve",
      side: 1,
      type: "infantry",
      count: 11000,
      commander: "Akhnoor garrison command",
      startPosition: { x: 70, y: 66 },
      color: "#3a5a8b",
    },
    {
      id: "ind-artillery",
      name: "Indian Counter-Battery Artillery",
      side: 1,
      type: "artillery",
      count: 84,
      commander: "Western Command artillery staff",
      startPosition: { x: 63, y: 74 },
      color: "#3a5a8b",
    },
  ],

  phases: [
    {
      title: "Grand Slam Opens at Chhamb",
      timestamp: "1 Sep, dawn",
      duration: "~2 hours",
      narration:
        "Pakistani artillery and armor-infantry teams open with concentrated fire and rapid assaults west of the Manawar Tawi. Indian forward troops are hit before full reinforcement and begin a controlled fallback from exposed positions.",
      movements: [
        {
          unitId: "pak-artillery",
          from: { x: 12, y: 74 },
          to: { x: 16, y: 70 },
          action: "bombard",
          significant: true,
          note: "Opening barrage on Indian forward belt.",
        },
        {
          unitId: "pak-armored-group",
          from: { x: 15, y: 58 },
          to: { x: 26, y: 56 },
          action: "advance",
          significant: true,
          note: "Armor punches toward Chhamb axis.",
        },
        {
          unitId: "ind-forward-infantry",
          from: { x: 34, y: 60 },
          to: { x: 38, y: 62 },
          action: "retreat",
          note: "Indian forward line trades space for cohesion.",
        },
      ],
      casualties: {
        side0: 700,
        side1: 1500,
        description: "Heavy opening bombardment and assault losses",
      },
      tacticalNote: "Pakistan seeks immediate tempo advantage before Indian reserves stabilize the corridor.",
    },
    {
      title: "Crossing Pressure and Flank Expansion",
      timestamp: "1 Sep, late morning",
      duration: "~3 hours",
      narration:
        "Pakistani lead elements force crossings and widen the breach near Chhamb. Indian armor attempts short local counterattacks but is pressured back by coordinated artillery and anti-armor fire.",
      movements: [
        {
          unitId: "pak-left-flank",
          from: { x: 11, y: 46 },
          to: { x: 24, y: 50 },
          curve: { control: { x: 17, y: 46 } },
          action: "flank",
          significant: true,
          note: "Left brigade expands northern shoulder of the breach.",
        },
        {
          unitId: "ind-armor-screen",
          from: { x: 43, y: 55 },
          to: { x: 37, y: 55 },
          action: "charge",
          note: "Indian armor counterattacks to slow crossings.",
        },
        {
          unitId: "ind-armor-screen",
          from: { x: 37, y: 55 },
          to: { x: 42, y: 57 },
          action: "retreat",
          damage: "heavy",
          note: "Counterattack blunted by layered Pakistani fires.",
        },
      ],
      casualties: {
        side0: 1200,
        side1: 2200,
        description: "Intense mid-range armor-infantry clashes",
      },
      tacticalNote: "Pakistani assault groups maintain momentum by combining artillery suppression with short armored thrusts.",
    },
    {
      title: "Fall of Chhamb Position",
      timestamp: "1 Sep, afternoon",
      duration: "~4 hours",
      narration:
        "Indian troops withdraw from the Chhamb defensive pocket as Pakistani formations consolidate road access for eastward advance. The battle transitions from breakthrough to pursuit toward Jaurian.",
      movements: [
        {
          unitId: "pak-main-infantry",
          from: { x: 18, y: 68 },
          to: { x: 30, y: 61 },
          action: "advance",
          significant: true,
          note: "Main infantry secures captured forward belt.",
        },
        {
          unitId: "pak-armored-group",
          from: { x: 26, y: 56 },
          to: { x: 38, y: 55 },
          action: "advance",
          significant: true,
          note: "Armor shifts onto Chhamb-Jaurian road.",
        },
        {
          unitId: "ind-forward-infantry",
          from: { x: 38, y: 62 },
          to: { x: 47, y: 63 },
          action: "retreat",
          note: "Indian forward troops regroup toward Jaurian line.",
        },
      ],
      casualties: {
        side0: 1600,
        side1: 2800,
        description: "High losses during withdrawal and road-fight actions",
      },
      tacticalNote: "Capturing Chhamb gives Pakistan tactical success and a direct route for continued offensive pressure.",
    },
    {
      title: "Command Transition and Tempo Drop",
      timestamp: "2 Sep",
      duration: "~1 day",
      narration:
        "A change in Pakistani operational command occurs during the offensive. While attacks continue, coordination pauses and regrouping consume time, allowing Indian formations to strengthen positions around Jaurian and Akhnoor.",
      movements: [
        {
          unitId: "pak-main-infantry",
          from: { x: 30, y: 61 },
          to: { x: 34, y: 60 },
          action: "hold",
          significant: true,
          note: "Assault line consolidates under new command cycle.",
        },
        {
          unitId: "ind-jaurian-line",
          from: { x: 52, y: 62 },
          to: { x: 49, y: 61 },
          action: "advance",
          note: "Indian defenders thicken Jaurian blocking line.",
        },
        {
          unitId: "ind-akhnoor-reserve",
          from: { x: 70, y: 66 },
          to: { x: 65, y: 64 },
          action: "advance",
          note: "Reserve shifts forward to protect bridge approaches.",
        },
      ],
      casualties: {
        side0: 500,
        side1: 700,
        description: "Mostly artillery and skirmish casualties during operational pause",
      },
      tacticalNote: "Operational tempo, not frontline collapse, becomes the decisive variable in this phase.",
    },
    {
      title: "Battle for Jaurian Approaches",
      timestamp: "3-4 Sep",
      duration: "~2 days",
      narration:
        "Pakistani units renew offensive pressure with armor and artillery support, forcing Indian withdrawals from some forward localities near Jaurian. Indian counter-battery fire and layered defense reduce exploitation speed.",
      movements: [
        {
          unitId: "pak-armored-group",
          from: { x: 38, y: 55 },
          to: { x: 50, y: 55 },
          curve: { control: { x: 44, y: 53 } },
          action: "charge",
          significant: true,
          note: "Renewed armored thrust into Jaurian sector.",
        },
        {
          unitId: "pak-artillery",
          from: { x: 16, y: 70 },
          to: { x: 24, y: 68 },
          action: "bombard",
          note: "Sustained fire on Indian blocking positions.",
        },
        {
          unitId: "ind-artillery",
          from: { x: 63, y: 74 },
          to: { x: 58, y: 73 },
          action: "bombard",
          significant: true,
          note: "Indian counter-battery and interdiction fires intensify.",
        },
      ],
      casualties: {
        side0: 2200,
        side1: 2600,
        description: "Prolonged artillery-heavy fighting around Jaurian axis",
      },
      tacticalNote: "Pakistan gains ground, but rising resistance prevents rapid conversion into an Akhnoor seizure.",
    },
    {
      title: "Approach to Akhnoor Stalls",
      timestamp: "5-6 Sep",
      duration: "~2 days",
      narration:
        "Pakistani spearheads approach the Akhnoor defensive system but face reinforced Indian lines, artillery concentration, and widening war fronts. The operation retains tactical gains west of Akhnoor but does not secure the bridgehead objective.",
      movements: [
        {
          unitId: "pak-armored-group",
          from: { x: 50, y: 55 },
          to: { x: 59, y: 57 },
          action: "advance",
          significant: true,
          note: "Spearhead reaches outer Akhnoor approach belt.",
        },
        {
          unitId: "ind-akhnoor-reserve",
          from: { x: 65, y: 64 },
          to: { x: 68, y: 62 },
          action: "hold",
          significant: true,
          note: "Indian reserve locks the bridgehead defense line.",
        },
        {
          unitId: "pak-armored-group",
          from: { x: 59, y: 57 },
          to: { x: 56, y: 58 },
          action: "hold",
          damage: "heavy",
          note: "Advance pauses under concentrated fire and delay.",
        },
      ],
      casualties: {
        side0: 1800,
        side1: 2100,
        description: "Hard fighting near the Akhnoor approach, no decisive breakthrough",
      },
      tacticalNote: "Without uninterrupted momentum, early tactical success cannot be translated into the operational objective.",
    },
  ],

  aftermath: {
    outcome:
      "Pakistan captured significant ground in the Chhamb-Jaurian sector but did not seize Akhnoor before the conflict broadened.",
    casualties: {
      side0: {
        dead: 4200,
        wounded: 5800,
        captured: 300,
      },
      side1: {
        dead: 5600,
        wounded: 7600,
        captured: 900,
      },
    },
    significance:
      "Operation Grand Slam is studied as a campaign where strong opening combined-arms execution produced local tactical success, but command transition and lost tempo reduced operational payoff. The battle underscored the strategic importance of Akhnoor communications and helped shape the wider escalation dynamics of the 1965 Indo-Pak war.",
  },
};
