import { BattleData } from "./types";

export const kargilData: BattleData = {
  battleMetadata: {
    name: "Kargil War (Pakistani Push), 1999",
    date: "May-July 1999",
    location: "Kargil-Dras-Batalik sector, Ladakh",
    belligerents: ["Pakistan (NLI-led intrusion force)", "India (Operation Vijay)"],
    commanders: [
      ["Pakistani Northern Light Infantry sector commanders", "Pakistan Army high command"],
      ["Lt Gen Krishan Pal", "Lt Gen Mohinder Puri", "Indian corps/division/brigade commanders"],
    ],
    outcome: "Pakistani forward positions progressively reduced; Indian recapture of key heights",
    scale: "High-altitude brigade/division-level mountain warfare across multiple ridgelines",
    environment: "snow",
  },

  context:
    "In spring 1999, Pakistani-backed forces, heavily associated with Northern Light Infantry elements, occupied a chain of high-altitude posts and ridgelines on the Indian side of the Line of Control in the Kargil-Dras-Batalik region. The tactical concept leveraged winter-vacated heights and extreme elevation to dominate valleys and threaten the Srinagar-Leh highway through observation and artillery correction.\\n\\nIndia responded with Operation Vijay, combining large-scale infantry assaults, concentrated artillery fire, and limited but important air power under severe altitude and terrain constraints. The campaign became a brutal sequence of uphill attacks against fortified sangars on narrow ridges where logistics, acclimatization, and weather were as decisive as firepower.\\n\\nThe battle study below focuses on the Pakistani push and its progressive erosion: early positional advantage, highway interdiction pressure, Indian shaping fires, and attritional recapture of key objectives including Tololing, Point 5140, Tiger Hill, and Batalik features.",

  terrain: [
    {
      type: "ridge",
      label: "Mashkoh-Dras High Ridge System",
      points: [
        { x: 0, y: 0 },
        { x: 100, y: 0 },
        { x: 100, y: 20 },
        { x: 86, y: 24 },
        { x: 71, y: 21 },
        { x: 56, y: 26 },
        { x: 40, y: 22 },
        { x: 24, y: 27 },
        { x: 10, y: 23 },
        { x: 0, y: 20 },
      ],
    },
    {
      type: "ridge",
      label: "Batalik-Kaksar Spur Belt",
      points: [
        { x: 72, y: 30 },
        { x: 100, y: 32 },
        { x: 100, y: 100 },
        { x: 84, y: 98 },
        { x: 79, y: 83 },
        { x: 82, y: 66 },
        { x: 77, y: 49 },
      ],
    },
    {
      type: "hill",
      label: "Tololing Complex",
      points: [
        { x: 30, y: 36 },
        { x: 38, y: 34 },
        { x: 42, y: 40 },
        { x: 37, y: 47 },
        { x: 29, y: 45 },
      ],
    },
    {
      type: "hill",
      label: "Tiger Hill Mass",
      points: [
        { x: 48, y: 30 },
        { x: 56, y: 27 },
        { x: 62, y: 33 },
        { x: 58, y: 42 },
        { x: 50, y: 39 },
      ],
    },
    {
      type: "hill",
      label: "Point 4875 Sector",
      points: [
        { x: 60, y: 44 },
        { x: 68, y: 42 },
        { x: 72, y: 49 },
        { x: 66, y: 56 },
        { x: 59, y: 53 },
      ],
    },
    {
      type: "snow",
      label: "Glaciated Slopes",
      points: [
        { x: 8, y: 18 },
        { x: 26, y: 16 },
        { x: 34, y: 24 },
        { x: 22, y: 31 },
        { x: 9, y: 28 },
      ],
    },
    {
      type: "road",
      label: "NH 1A (Srinagar-Leh Highway)",
      points: [
        { x: 4, y: 74 },
        { x: 18, y: 72 },
        { x: 34, y: 70 },
        { x: 50, y: 69 },
        { x: 66, y: 68 },
        { x: 82, y: 68 },
        { x: 98, y: 69 },
      ],
      width: 1.1,
    },
    {
      type: "road",
      label: "Dras-Tololing Climb Route",
      points: [
        { x: 22, y: 74 },
        { x: 26, y: 62 },
        { x: 30, y: 52 },
        { x: 34, y: 43 },
      ],
      width: 0.7,
    },
    {
      type: "fortification",
      label: "Pakistani Sangar Line (Dras Heights)",
      points: [
        { x: 24, y: 34 },
        { x: 60, y: 34 },
        { x: 60, y: 38 },
        { x: 24, y: 38 },
      ],
    },
    {
      type: "fortification",
      label: "Pakistani Forward Pickets (Batalik)",
      points: [
        { x: 76, y: 46 },
        { x: 93, y: 46 },
        { x: 93, y: 50 },
        { x: 76, y: 50 },
      ],
    },
  ],

  forces: [
    {
      id: "pak-nli-dras",
      name: "Pak NLI Dras Sector Groups",
      side: 0,
      type: "infantry",
      count: 2200,
      commander: "NLI sector commanders",
      startPosition: { x: 39, y: 35 },
      color: "#8b3a3a",
    },
    {
      id: "pak-nli-batalik",
      name: "Pak NLI Batalik Detachments",
      side: 0,
      type: "infantry",
      count: 1400,
      commander: "Forward post commanders",
      startPosition: { x: 84, y: 48 },
      color: "#8b3a3a",
    },
    {
      id: "pak-mortar-groups",
      name: "Pak Mortar and Support Weapon Cells",
      side: 0,
      type: "artillery",
      count: 42,
      commander: "Sector fire controllers",
      startPosition: { x: 58, y: 31 },
      color: "#8b3a3a",
    },
    {
      id: "pak-reserve-packets",
      name: "Pak High Ridge Reserve Packets",
      side: 0,
      type: "infantry",
      count: 900,
      commander: "Local reserve officers",
      startPosition: { x: 69, y: 30 },
      color: "#8b3a3a",
    },

    {
      id: "ind-infantry-dras",
      name: "Indian Dras Assault Battalions",
      side: 1,
      type: "infantry",
      count: 3400,
      commander: "56 Mountain Brigade officers",
      startPosition: { x: 30, y: 70 },
      color: "#3a5a8b",
    },
    {
      id: "ind-infantry-batalik",
      name: "Indian Batalik Assault Groups",
      side: 1,
      type: "infantry",
      count: 2600,
      commander: "Batalik sub-sector command",
      startPosition: { x: 78, y: 73 },
      color: "#3a5a8b",
    },
    {
      id: "ind-artillery-mass",
      name: "Indian Artillery Mass (Bofors-led)",
      side: 1,
      type: "artillery",
      count: 120,
      commander: "Corps artillery command",
      startPosition: { x: 52, y: 78 },
      color: "#3a5a8b",
    },
    {
      id: "ind-special-climbers",
      name: "Indian Ghatak/High-Altitude Teams",
      side: 1,
      type: "infantry",
      count: 420,
      commander: "Assault company leaders",
      startPosition: { x: 42, y: 74 },
      color: "#3a5a8b",
    },
    {
      id: "ind-air-strike-group",
      name: "Indian Air Strike Package",
      side: 1,
      type: "aircraft",
      count: 26,
      commander: "Operation Safed Sagar planners",
      startPosition: { x: 50, y: 86 },
      color: "#3a5a8b",
    },
  ],

  phases: [
    {
      title: "High-Altitude Occupation and Concealment",
      timestamp: "Early May",
      duration: "~5 days",
      narration:
        "Pakistani NLI-led elements occupy vacated winter heights across Dras, Kaksar, and Batalik sectors. They establish sangars and observation posts overlooking key Indian approach lines. Initial occupation prioritizes concealment and depth over overt fire engagements.",
      movements: [
        {
          unitId: "pak-nli-dras",
          from: { x: 39, y: 35 },
          to: { x: 44, y: 33 },
          action: "advance",
          significant: true,
          note: "Forward sangars deepen along Tololing-Tiger Hill belt.",
        },
        {
          unitId: "pak-nli-batalik",
          from: { x: 84, y: 48 },
          to: { x: 88, y: 46 },
          action: "advance",
          note: "Batalik pickets extend ridge occupancy.",
        },
      ],
      casualties: {
        side0: 20,
        side1: 15,
        description: "Minor early patrol clashes in severe weather",
      },
      tacticalNote: "In mountain war, early positional seizure can create disproportionate tactical leverage.",
    },
    {
      title: "Observation Dominance Over NH 1A",
      timestamp: "Mid May",
      duration: "~1 week",
      narration:
        "From elevated posts, Pakistani observers begin directing fires and threatening movement on the Srinagar-Leh highway corridor. Indian logistic movement becomes more constrained and reconnaissance pressure increases. The campaign shifts from localized intrusion to operational concern.",
      movements: [
        {
          unitId: "pak-mortar-groups",
          from: { x: 58, y: 31 },
          to: { x: 55, y: 34 },
          action: "bombard",
          significant: true,
          note: "Interdiction fire attempts on highway traffic windows.",
        },
        {
          unitId: "ind-artillery-mass",
          from: { x: 52, y: 78 },
          to: { x: 52, y: 76 },
          action: "hold",
          note: "Indian gun areas prepare counter-battery response.",
        },
      ],
      casualties: {
        side0: 35,
        side1: 85,
        description: "Highway and forward post fire incidents rise",
      },
      tacticalNote: "High ground plus observers turns indirect fire into a strategic interdiction tool.",
    },
    {
      title: "Indian Build-Up and Sector Clarification",
      timestamp: "Late May",
      duration: "~6 days",
      narration:
        "India commits additional infantry and artillery, mapping intrusion depth across multiple ridges. Initial probing attacks reveal hardened sangars and steep final approaches. Force concentration begins around Dras and Batalik for deliberate recapture operations.",
      movements: [
        {
          unitId: "ind-infantry-dras",
          from: { x: 30, y: 70 },
          to: { x: 33, y: 64 },
          action: "advance",
          significant: true,
          note: "Dras battalions stage closer to assault start lines.",
        },
        {
          unitId: "ind-infantry-batalik",
          from: { x: 78, y: 73 },
          to: { x: 80, y: 66 },
          action: "advance",
          note: "Batalik groups move into climb bases.",
        },
      ],
      casualties: {
        side0: 55,
        side1: 140,
        description: "Recon-in-force actions prove costly on exposed slopes",
      },
      tacticalNote: "Terrain intelligence and route rehearsal are prerequisites for uphill assault success.",
    },
    {
      title: "Artillery Shaping and Initial Tololing Attempts",
      timestamp: "Early June",
      duration: "~1 week",
      narration:
        "Indian artillery massing escalates, targeting crest lines and supply ledges. Initial infantry attempts at Tololing face heavy resistance and difficult gradients. Pakistani defenders trade space minimally, relying on pre-sited fields of fire.",
      movements: [
        {
          unitId: "ind-artillery-mass",
          from: { x: 52, y: 76 },
          to: { x: 49, y: 72 },
          action: "bombard",
          significant: true,
          note: "Sustained shaping fires on Tololing-Tiger Hill features.",
        },
        {
          unitId: "ind-infantry-dras",
          from: { x: 33, y: 64 },
          to: { x: 35, y: 56 },
          action: "charge",
          note: "Early Tololing assaults test defensive belts.",
        },
        {
          unitId: "pak-nli-dras",
          from: { x: 44, y: 33 },
          to: { x: 42, y: 36 },
          action: "hold",
          significant: true,
          note: "Pakistani sangars absorb and repulse frontal pushes.",
        },
      ],
      casualties: {
        side0: 130,
        side1: 280,
        description: "High attrition during first major uphill attacks",
      },
      tacticalNote: "Frontal mountain assaults without flank access incur severe cost against dug-in defenders.",
    },
    {
      title: "Tololing Recapture Momentum",
      timestamp: "Mid June",
      duration: "~4 days",
      narration:
        "After repeated attempts and heavy preparatory fire, Indian assault elements secure key portions of the Tololing complex. Pakistani defenders begin partial fallback to secondary sangars. The local tactical initiative shifts toward Indian forces in Dras.",
      movements: [
        {
          unitId: "ind-special-climbers",
          from: { x: 42, y: 74 },
          to: { x: 37, y: 50 },
          curve: { control: { x: 39, y: 61 } },
          action: "flank",
          significant: true,
          note: "Night climb teams outmaneuver direct fire lanes.",
        },
        {
          unitId: "ind-infantry-dras",
          from: { x: 35, y: 56 },
          to: { x: 36, y: 49 },
          action: "advance",
          significant: true,
          note: "Main assault elements consolidate captured ledges.",
        },
        {
          unitId: "pak-nli-dras",
          from: { x: 42, y: 36 },
          to: { x: 46, y: 34 },
          action: "retreat",
          damage: "heavy",
          note: "Defenders withdraw to adjacent high points.",
        },
      ],
      casualties: {
        side0: 210,
        side1: 240,
        description: "Intense close-range fighting for crest control",
      },
      tacticalNote: "Limited local flanking on steep terrain can break otherwise stable defense nodes.",
    },
    {
      title: "Point 5140 and Adjacent Features Pressured",
      timestamp: "Late June",
      duration: "~5 days",
      narration:
        "Indian units exploit Tololing gains to push toward Point 5140 and neighboring positions. Pakistani reserves are fed into the line but face increasing artillery saturation. Defensive coherence remains dangerous yet increasingly strained.",
      movements: [
        {
          unitId: "ind-infantry-dras",
          from: { x: 36, y: 49 },
          to: { x: 41, y: 43 },
          action: "advance",
          significant: true,
          note: "Indian progression links Tololing gains to next objective belt.",
        },
        {
          unitId: "pak-reserve-packets",
          from: { x: 69, y: 30 },
          to: { x: 58, y: 36 },
          action: "advance",
          note: "Reserve packets reinforce thinning ridge defenses.",
        },
        {
          unitId: "ind-artillery-mass",
          from: { x: 49, y: 72 },
          to: { x: 47, y: 70 },
          action: "bombard",
          note: "Counter-sangar fires intensify before assault windows.",
        },
      ],
      casualties: {
        side0: 260,
        side1: 220,
        description: "Sustained attrition along linked ridgeline objectives",
      },
      tacticalNote: "Mountain defense can hold tactically, but cumulative artillery and supply stress degrade staying power.",
    },
    {
      title: "Tiger Hill Isolation Operations",
      timestamp: "End June - Early July",
      duration: "~6 days",
      narration:
        "Indian command isolates Tiger Hill through multi-axis pressure and persistent shelling. Pakistani posts remain dangerous but are increasingly segmented by disrupted lateral movement. Air and artillery coordination tightens against identifiable strongpoints.",
      movements: [
        {
          unitId: "ind-air-strike-group",
          from: { x: 50, y: 86 },
          to: { x: 54, y: 58 },
          action: "bombard",
          significant: true,
          note: "Air strikes support suppression of dominant crest positions.",
        },
        {
          unitId: "ind-special-climbers",
          from: { x: 37, y: 50 },
          to: { x: 52, y: 41 },
          curve: { control: { x: 45, y: 45 } },
          action: "flank",
          note: "Climber teams probe alternate Tiger Hill approaches.",
        },
        {
          unitId: "pak-nli-dras",
          from: { x: 46, y: 34 },
          to: { x: 52, y: 33 },
          action: "hold",
          significant: true,
          note: "Pakistani defenders consolidate around Tiger Hill mass.",
        },
      ],
      casualties: {
        side0: 180,
        side1: 210,
        description: "High-intensity suppression and infiltration losses",
      },
      tacticalNote: "Isolating a mountain objective often matters more than immediate frontal capture.",
    },
    {
      title: "Tiger Hill Recapture",
      timestamp: "Early July",
      duration: "~3 days",
      narration:
        "Coordinated night assaults and sustained support fires culminate in Indian seizure of Tiger Hill positions. Pakistani defenders attempt local counter-pressure but lose dominant observation advantage over key sectors. Psychological and operational momentum shifts sharply.",
      movements: [
        {
          unitId: "ind-infantry-dras",
          from: { x: 41, y: 43 },
          to: { x: 54, y: 36 },
          action: "charge",
          significant: true,
          note: "Main assault wave reaches Tiger Hill crest belt.",
        },
        {
          unitId: "ind-special-climbers",
          from: { x: 52, y: 41 },
          to: { x: 56, y: 34 },
          action: "encircle",
          significant: true,
          note: "Flanking teams seal rear egress routes.",
        },
        {
          unitId: "pak-nli-dras",
          from: { x: 52, y: 33 },
          to: { x: 60, y: 35 },
          action: "retreat",
          damage: "heavy",
          significant: true,
          note: "Tiger Hill defenders withdraw under pressure.",
        },
      ],
      casualties: {
        side0: 240,
        side1: 260,
        description: "Very heavy losses in close crest fighting",
      },
      tacticalNote: "Capture of a dominant height can reframe the entire operational geometry.",
    },
    {
      title: "Batalik and Point 4875 Reduction",
      timestamp: "Mid July",
      duration: "~1 week",
      narration:
        "Indian units intensify operations in Batalik and around Point 4875, clearing fortified pockets and severing remaining Pakistani local support lines. Pakistani detachments conduct stubborn holding actions but increasingly lose mutually supporting positions.",
      movements: [
        {
          unitId: "ind-infantry-batalik",
          from: { x: 80, y: 66 },
          to: { x: 84, y: 56 },
          action: "advance",
          significant: true,
          note: "Batalik assaults compress forward picket belt.",
        },
        {
          unitId: "pak-nli-batalik",
          from: { x: 88, y: 46 },
          to: { x: 90, y: 52 },
          action: "retreat",
          damage: "heavy",
          note: "Pakistani Batalik posts fall back to last ledges.",
        },
        {
          unitId: "ind-artillery-mass",
          from: { x: 47, y: 70 },
          to: { x: 63, y: 66 },
          action: "bombard",
          note: "Fire support shifts to eastern objectives.",
        },
      ],
      casualties: {
        side0: 210,
        side1: 190,
        description: "Attritional fighting across multiple eastern spurs",
      },
      tacticalNote: "Sequential reduction of satellite positions prevents reconstitution of ridge defense.",
    },
    {
      title: "Disengagement and Loss of Forward Complexes",
      timestamp: "Late July",
      duration: "~5 days",
      narration:
        "Under combined military and diplomatic pressure, Pakistani forward-held complexes are progressively vacated or overrun. Indian forces reoccupy remaining strategic points and restore greater highway security. The campaign closes with Pakistani tactical initiative exhausted.",
      movements: [
        {
          unitId: "pak-reserve-packets",
          from: { x: 58, y: 36 },
          to: { x: 70, y: 28 },
          action: "retreat",
          damage: "heavy",
          significant: true,
          note: "Residual reserve groups disengage from exposed crests.",
        },
        {
          unitId: "pak-nli-batalik",
          from: { x: 90, y: 52 },
          to: { x: 95, y: 43 },
          action: "retreat",
          note: "Remaining eastern detachments withdraw from forward ledges.",
        },
        {
          unitId: "ind-infantry-dras",
          from: { x: 54, y: 36 },
          to: { x: 58, y: 32 },
          action: "advance",
          significant: true,
          note: "Indian units secure final critical Dras heights.",
        },
      ],
      casualties: {
        side0: 170,
        side1: 90,
        description: "Rear-guard losses during disengagement and final clearing actions",
      },
      tacticalNote: "Once dominant heights are lost, mountain intrusions become difficult to sustain operationally.",
    },
  ],

  aftermath: {
    outcome:
      "Pakistani forward push achieved temporary high-ground leverage but was rolled back through sustained Indian recapture operations.",
    casualties: {
      side0: {
        dead: 700,
        wounded: 1100,
        captured: 40,
      },
      side1: {
        dead: 527,
        wounded: 1363,
        captured: 30,
      },
    },
    significance:
      "Kargil underscored that high-altitude tactical surprise can yield early advantage, but sustaining exposed ridge occupations against superior artillery, coordinated infantry assaults, and political-strategic pressure is difficult. The campaign reshaped Indian mountain warfare doctrine, surveillance emphasis, and artillery-infantry integration, while becoming a major strategic and diplomatic inflection point in South Asian military history.",
  },
};
