import { BattleData } from "./types";

export const yarmoukData: BattleData = {
  battleMetadata: {
    name: "Battle of Yarmouk",
    date: "August 636 CE",
    location: "Yarmouk plateau near the Wadi al-Raqqad and Yarmouk ravines",
    belligerents: ["Rashidun Caliphate", "Byzantine Empire"],
    commanders: [
      ["Khalid ibn al-Walid", "Abu Ubayda ibn al-Jarrah", "Yazid ibn Abi Sufyan"],
      ["Vahan", "Theodore Trithyrius", "Jabalah ibn al-Ayham"],
    ],
    outcome: "Decisive Rashidun victory; Byzantine field army in Syria broken",
    scale: "Approx. 25,000-40,000 Rashidun vs 60,000-80,000 Byzantine (estimates vary)",
    environment: "desert",
  },

  context:
    "The Battle of Yarmouk was the decisive contest for control of Syria between the Rashidun Caliphate and the Byzantine Empire. After earlier campaigning and maneuver warfare across the Levant, both sides concentrated major forces on a plateau bounded by deep ravines and wadis, terrain that limited retreat options and magnified command decisions.\\n\\nByzantine commanders aimed to use numerical advantage through broad-front pressure and sequential wing attacks, while Khalid ibn al-Walid sought to preserve cohesion, counter local penetrations, and create an operationally decisive cavalry stroke. The battlefield's broken edges and narrow exits made discipline and reserve timing critical.\\n\\nOver several days, repeated Byzantine assaults failed to produce collapse. Rashidun forces absorbed shocks, re-formed lines, and ultimately executed a coordinated mounted envelopment that turned local success into general Byzantine disintegration, with ravine geography worsening the retreat.",

  terrain: [
    {
      type: "ridge",
      label: "Northern Plateau Edge",
      points: [
        { x: 0, y: 0 },
        { x: 100, y: 0 },
        { x: 100, y: 18 },
        { x: 82, y: 22 },
        { x: 64, y: 19 },
        { x: 46, y: 23 },
        { x: 28, y: 19 },
        { x: 12, y: 22 },
        { x: 0, y: 18 },
      ],
    },
    {
      type: "marsh",
      label: "Wadi al-Raqqad Ravine Belt",
      points: [
        { x: 82, y: 28 },
        { x: 100, y: 30 },
        { x: 100, y: 82 },
        { x: 90, y: 80 },
        { x: 86, y: 64 },
        { x: 88, y: 48 },
        { x: 84, y: 36 },
      ],
    },
    {
      type: "marsh",
      label: "Yarmouk Gorge Approaches",
      points: [
        { x: 0, y: 70 },
        { x: 18, y: 68 },
        { x: 24, y: 78 },
        { x: 20, y: 92 },
        { x: 0, y: 100 },
      ],
    },
    {
      type: "plain",
      label: "Yarmouk Battle Plain",
      points: [
        { x: 10, y: 24 },
        { x: 88, y: 24 },
        { x: 88, y: 86 },
        { x: 10, y: 86 },
      ],
    },
    {
      type: "road",
      label: "Jabiya-Damascus Axis",
      points: [
        { x: 12, y: 10 },
        { x: 24, y: 22 },
        { x: 38, y: 34 },
        { x: 52, y: 46 },
        { x: 68, y: 58 },
        { x: 84, y: 70 },
      ],
      width: 0.7,
    },
    {
      type: "hill",
      label: "Ayn al-Dhakar Rise",
      points: [
        { x: 44, y: 30 },
        { x: 52, y: 28 },
        { x: 58, y: 34 },
        { x: 54, y: 42 },
        { x: 46, y: 39 },
      ],
    },
    {
      type: "fortification",
      label: "Rashidun Rear Camp Line",
      points: [
        { x: 26, y: 76 },
        { x: 66, y: 76 },
        { x: 66, y: 80 },
        { x: 26, y: 80 },
      ],
    },
  ],

  forces: [
    {
      id: "rash-center",
      name: "Rashidun Center Infantry",
      side: 0,
      type: "infantry",
      count: 14000,
      commander: "Abu Ubayda",
      startPosition: { x: 50, y: 68 },
      color: "#8b3a3a",
    },
    {
      id: "rash-left-wing",
      name: "Rashidun Left Wing",
      side: 0,
      type: "infantry",
      count: 7000,
      commander: "Yazid ibn Abi Sufyan",
      startPosition: { x: 32, y: 66 },
      color: "#8b3a3a",
    },
    {
      id: "rash-right-wing",
      name: "Rashidun Right Wing",
      side: 0,
      type: "infantry",
      count: 7000,
      commander: "Amr ibn al-As",
      startPosition: { x: 68, y: 66 },
      color: "#8b3a3a",
    },
    {
      id: "rash-mobile-guard",
      name: "Khalid's Mobile Guard Cavalry",
      side: 0,
      type: "cavalry",
      count: 5000,
      commander: "Khalid ibn al-Walid",
      startPosition: { x: 50, y: 74 },
      color: "#8b3a3a",
    },
    {
      id: "rash-archers",
      name: "Rashidun Archer Screen",
      side: 0,
      type: "archers",
      count: 2500,
      commander: "Field emirs",
      startPosition: { x: 50, y: 62 },
      color: "#8b3a3a",
    },

    {
      id: "byz-center",
      name: "Byzantine Center Army",
      side: 1,
      type: "infantry",
      count: 28000,
      commander: "Vahan",
      startPosition: { x: 50, y: 34 },
      color: "#3a5a8b",
    },
    {
      id: "byz-left",
      name: "Byzantine Left Wing",
      side: 1,
      type: "infantry",
      count: 13000,
      commander: "Gregory",
      startPosition: { x: 30, y: 36 },
      color: "#3a5a8b",
    },
    {
      id: "byz-right",
      name: "Byzantine Right Wing",
      side: 1,
      type: "infantry",
      count: 13000,
      commander: "Qanateer",
      startPosition: { x: 70, y: 36 },
      color: "#3a5a8b",
    },
    {
      id: "byz-cavalry",
      name: "Byzantine Heavy Cavalry",
      side: 1,
      type: "cavalry",
      count: 7000,
      commander: "Theodore",
      startPosition: { x: 54, y: 28 },
      color: "#3a5a8b",
    },
    {
      id: "byz-archers",
      name: "Byzantine Archer Line",
      side: 1,
      type: "archers",
      count: 5000,
      commander: "Imperial officers",
      startPosition: { x: 50, y: 40 },
      color: "#3a5a8b",
    },
  ],

  phases: [
    {
      title: "Initial Deployment on the Plateau",
      timestamp: "Day 1, morning",
      duration: "~1 hour",
      narration:
        "Both armies align along a broad front on the Yarmouk plateau. Byzantine command prepares pressure attacks on multiple sectors, while Rashidun command keeps a compact, reserve-backed posture. Terrain edges and ravines already constrain safe retreat corridors.",
      movements: [
        {
          unitId: "byz-center",
          from: { x: 50, y: 34 },
          to: { x: 50, y: 40 },
          action: "advance",
          significant: true,
          note: "Byzantine center opens with broad forward pressure.",
        },
        {
          unitId: "rash-mobile-guard",
          from: { x: 50, y: 74 },
          to: { x: 50, y: 72 },
          action: "hold",
          note: "Mobile reserve remains uncommitted behind main line.",
        },
      ],
      casualties: { side0: 180, side1: 220, description: "Opening skirmish losses" },
      tacticalNote: "Reserve conservation early in battle preserves options for later decisive action.",
    },
    {
      title: "Byzantine Wing Pressure",
      timestamp: "Day 1, midday",
      duration: "~2 hours",
      narration:
        "Byzantine wings push aggressively, aiming to bend Rashidun flanks and create separation from the center. Rashidun wings give limited ground but remain cohesive. Missile exchanges intensify across the line.",
      movements: [
        {
          unitId: "byz-left",
          from: { x: 30, y: 36 },
          to: { x: 28, y: 50 },
          action: "charge",
          significant: true,
          note: "Byzantine left attempts to crush Rashidun flank.",
        },
        {
          unitId: "byz-right",
          from: { x: 70, y: 36 },
          to: { x: 72, y: 50 },
          action: "charge",
          note: "Right wing mirrors pressure against opposite sector.",
        },
        {
          unitId: "rash-left-wing",
          from: { x: 32, y: 66 },
          to: { x: 31, y: 60 },
          action: "retreat",
          note: "Controlled fallback preserves line integrity.",
        },
      ],
      casualties: { side0: 650, side1: 720, description: "Heavy flank fighting and missile attrition" },
      tacticalNote: "Elastic defense can absorb stronger attacks without structural collapse.",
    },
    {
      title: "Center Binding and Counter-Rallies",
      timestamp: "Day 2",
      duration: "~1 day",
      narration:
        "The Byzantine center presses repeatedly to pin Rashidun infantry while wings continue pressure. Rashidun commanders cycle local counterattacks to restore lost frontage. Neither side achieves breakthrough, but fatigue and losses rise rapidly.",
      movements: [
        {
          unitId: "byz-center",
          from: { x: 50, y: 40 },
          to: { x: 50, y: 48 },
          action: "advance",
          significant: true,
          note: "Byzantine center tries to lock Rashidun core in place.",
        },
        {
          unitId: "rash-center",
          from: { x: 50, y: 68 },
          to: { x: 50, y: 62 },
          action: "hold",
          significant: true,
          note: "Rashidun center absorbs impact and reforms.",
        },
        {
          unitId: "rash-mobile-guard",
          from: { x: 50, y: 72 },
          to: { x: 46, y: 64 },
          action: "flank",
          note: "Reserve cavalry conducts local stabilizing counterstroke.",
        },
      ],
      casualties: { side0: 1200, side1: 1400, description: "Sustained close combat across center sectors" },
      tacticalNote: "Local counter-rallies prevent tactical setbacks from becoming operational collapse.",
    },
    {
      title: "Missile Saturation and Line Distortion",
      timestamp: "Day 3",
      duration: "~1 day",
      narration:
        "Intense archery and probing assaults distort both front lines. Byzantine command seeks to create exploitable seams between Rashidun center and wings. Rashidun response prioritizes reconnecting sectors and limiting cavalry exposure.",
      movements: [
        {
          unitId: "byz-archers",
          from: { x: 50, y: 40 },
          to: { x: 50, y: 46 },
          action: "bombard",
          significant: true,
          note: "Byzantine archers intensify suppression on center-front.",
        },
        {
          unitId: "rash-archers",
          from: { x: 50, y: 62 },
          to: { x: 50, y: 58 },
          action: "bombard",
          note: "Rashidun missile fire supports sector recovery.",
        },
        {
          unitId: "rash-right-wing",
          from: { x: 68, y: 66 },
          to: { x: 66, y: 61 },
          action: "hold",
          note: "Right wing contracts to maintain connected frontage.",
        },
      ],
      casualties: { side0: 900, side1: 980, description: "Severe ranged and close-quarter losses" },
      tacticalNote: "Maintaining lateral connectivity between sectors is central in large-front battles.",
    },
    {
      title: "Byzantine Offensive Peak",
      timestamp: "Day 4, morning",
      duration: "~4 hours",
      narration:
        "Byzantine forces mount their strongest coordinated push, briefly driving parts of the Rashidun wings backward. Crisis management by field commanders prevents rupture. Khalid begins concentrating cavalry for a theater-level counterstroke.",
      movements: [
        {
          unitId: "byz-left",
          from: { x: 28, y: 50 },
          to: { x: 26, y: 58 },
          action: "advance",
          significant: true,
          note: "Byzantine pressure deepens against Rashidun left.",
        },
        {
          unitId: "byz-right",
          from: { x: 72, y: 50 },
          to: { x: 74, y: 58 },
          action: "advance",
          note: "Right wing matches push to widen tactical gains.",
        },
        {
          unitId: "rash-mobile-guard",
          from: { x: 46, y: 64 },
          to: { x: 52, y: 66 },
          action: "hold",
          significant: true,
          note: "Cavalry mass reorganizes for decisive employment.",
        },
      ],
      casualties: { side0: 1150, side1: 1000, description: "Highest pressure phase before reversal" },
      tacticalNote: "An attacker’s peak momentum often creates exposure if not immediately decisive.",
    },
    {
      title: "Rashidun Cavalry Concentration",
      timestamp: "Day 4, afternoon",
      duration: "~3 hours",
      narration:
        "Khalid consolidates dispersed mounted elements into a concentrated striking force. Byzantine cavalry is drawn into contested maneuver zones and loses freedom of movement. The battle transitions from linear attrition toward operational maneuver.",
      movements: [
        {
          unitId: "rash-mobile-guard",
          from: { x: 52, y: 66 },
          to: { x: 60, y: 56 },
          curve: { control: { x: 58, y: 62 } },
          action: "flank",
          significant: true,
          note: "Mobile Guard swings to challenge Byzantine mounted screen.",
        },
        {
          unitId: "byz-cavalry",
          from: { x: 54, y: 28 },
          to: { x: 60, y: 44 },
          action: "advance",
          significant: true,
          note: "Byzantine cavalry commits to block envelopment setup.",
        },
      ],
      casualties: { side0: 700, side1: 950, description: "Mounted clashes and command friction increase" },
      tacticalNote: "Cavalry concentration can reframe battle geometry faster than infantry attrition.",
    },
    {
      title: "Byzantine Cavalry Setback",
      timestamp: "Day 5, morning",
      duration: "~4 hours",
      narration:
        "Rashidun cavalry gains local superiority and pushes Byzantine mounted forces off decisive ground. Byzantine infantry wings lose mounted cover and become more vulnerable to lateral attack. Command cohesion begins to fray under rapid tempo shifts.",
      movements: [
        {
          unitId: "rash-mobile-guard",
          from: { x: 60, y: 56 },
          to: { x: 66, y: 46 },
          action: "charge",
          significant: true,
          note: "Khalid's cavalry breaks mounted opposition in key sector.",
        },
        {
          unitId: "byz-cavalry",
          from: { x: 60, y: 44 },
          to: { x: 68, y: 34 },
          action: "retreat",
          damage: "heavy",
          note: "Byzantine cavalry displaced from battle-critical ground.",
        },
      ],
      casualties: { side0: 620, side1: 1300, description: "Byzantine mounted arm suffers severe losses" },
      tacticalNote: "Loss of cavalry screen exposes infantry wings to envelopment dynamics.",
    },
    {
      title: "Coordinated Rashidun Envelopment",
      timestamp: "Day 5, midday",
      duration: "~3 hours",
      narration:
        "With Byzantine cavalry degraded, Rashidun forces execute coordinated flank and front pressure. Byzantine wings struggle to maintain alignment with the center. Retreat routes narrow as units are compressed toward hazardous terrain edges.",
      movements: [
        {
          unitId: "rash-mobile-guard",
          from: { x: 66, y: 46 },
          to: { x: 74, y: 42 },
          action: "encircle",
          significant: true,
          note: "Rashidun cavalry turns Byzantine right-rear sectors.",
        },
        {
          unitId: "rash-center",
          from: { x: 50, y: 62 },
          to: { x: 50, y: 56 },
          action: "advance",
          note: "Center advances as wings come under envelopment pressure.",
        },
        {
          unitId: "byz-right",
          from: { x: 74, y: 58 },
          to: { x: 80, y: 60 },
          action: "rout",
          damage: "heavy",
          significant: true,
          note: "Right wing cohesion breaks under multi-axis pressure.",
        },
      ],
      casualties: { side0: 780, side1: 2200, description: "Major Byzantine losses during collapse onset" },
      tacticalNote: "Simultaneous frontal bind and flank turn is a classic route to battlefield decision.",
    },
    {
      title: "General Byzantine Collapse",
      timestamp: "Day 5, afternoon",
      duration: "~2 hours",
      narration:
        "Byzantine command and control degrades into fragmented withdrawals. Units attempting to disengage are funneled toward ravine approaches, worsening disorder. Rashidun pressure remains coordinated enough to prevent full re-formation.",
      movements: [
        {
          unitId: "byz-center",
          from: { x: 50, y: 48 },
          to: { x: 58, y: 50 },
          action: "retreat",
          damage: "heavy",
          significant: true,
          note: "Center begins disorganized fallback under converging attacks.",
        },
        {
          unitId: "byz-left",
          from: { x: 26, y: 58 },
          to: { x: 20, y: 66 },
          action: "retreat",
          note: "Left wing withdraws toward constricted terrain exits.",
        },
        {
          unitId: "rash-right-wing",
          from: { x: 66, y: 61 },
          to: { x: 70, y: 56 },
          action: "advance",
          note: "Rashidun infantry sustains pressure on collapsing sectors.",
        },
      ],
      casualties: { side0: 540, side1: 3000, description: "Retreat phase casualties surge dramatically" },
      tacticalNote: "Once retreat channels compress, losses can spike independent of direct tactical skill.",
    },
    {
      title: "Field Secured by Rashidun Forces",
      timestamp: "Day 5, evening",
      duration: "~1 hour",
      narration:
        "Remaining Byzantine resistance fragments and disperses. Rashidun forces secure the plateau and key approaches, ending coherent imperial field opposition in the sector. The strategic balance in Syria shifts decisively.",
      movements: [
        {
          unitId: "rash-center",
          from: { x: 50, y: 56 },
          to: { x: 52, y: 50 },
          action: "advance",
          significant: true,
          note: "Rashidun center occupies abandoned Byzantine main line.",
        },
        {
          unitId: "rash-mobile-guard",
          from: { x: 74, y: 42 },
          to: { x: 78, y: 38 },
          action: "hold",
          note: "Cavalry screens against residual regroup attempts.",
        },
      ],
      casualties: { side0: 300, side1: 1600, description: "Final losses during disintegration and pursuit" },
      tacticalNote: "Operational decision comes from cumulative control of tempo, reserves, and terrain exits.",
    },
  ],

  aftermath: {
    outcome:
      "Rashidun decisive victory at Yarmouk, destroying Byzantine capacity to hold Syria in the immediate term.",
    casualties: {
      side0: { dead: 4000, wounded: 5500, captured: 300 },
      side1: { dead: 20000, wounded: 12000, captured: 5000 },
    },
    significance:
      "Yarmouk was one of late antiquity's decisive battles. It ended effective Byzantine military dominance in Syria, enabled rapid Rashidun consolidation in the Levant, and demonstrated the battlefield value of reserve management, mounted maneuver, and terrain-aware operational timing.",
  },
};
